import backendTask from "@/img/BackendTask.webp";
import backendREST from "@/img/Backend_RESTFULL.webp";
import heroApp from "@/img/HeroApp.webp";
import calculadoraSistemaNumerico from "@/img/calculadoraSistemaNumerico.webp";
import cashBank from "@/img/cashBank.webp";
import expenseTracker from "@/img/expense-tracker-cli.webp";
import inventarioKinder from "@/img/inventarioKinder.webp";
import kheldeIO from "@/img/kheldeio.webp";
import mathGame from "@/img/mathgame.webp";
import portafolio from "@/img/portafolio.webp";
import taskTracker from "@/img/taskTracker.webp";
import type { DataProjects } from "@/types/typesDataproyectos";

export const dataProyectosEN: DataProjects[] = [
  {
    id: "backend-task",
    title: "BackendTask",
    description:
      "Backend My Task Board devchallenges.io with full CRUD in MySQL and PostgreSQL, including task status retrieval based on the task.",
    topics: [
      "backend-api",
      "crud-application",
      "expressjs",
      "mysql",
      "mysql2",
      "node",
      "nodejs",
      "postgres",
      "postgresql",
      "dotenv",
      "nodemon",
      "pg",
      "swagger-jsdoc",
      "swagger-ui-express",
    ],
    link: "https://github.com/muke78/BackendTask",
    img: backendTask.src,
    fork: false,
  },
  {
    id: "backend-rest-full",
    title: "Backend_RESTFULL",
    description:
      "Backend with Express and Nodemon, including CRUD, JWT authentication, Swagger, file uploads, and later a React interface with Zustand and Tanstack Query.",
    topics: [
      "@formkit/tempo",
      "@trivago/prettier-plugin-sort-imports",
      "argon2",
      "backend",
      "backend-api",
      "crud-application",
      "express",
      "jwt-authentication",
      "jwt-token",
      "mysql2",
      "node",
      "nodemon",
      "rest-api",
      "swagger-jsdoc",
      "swagger-ui-express",
    ],
    link: "https://github.com/muke78/Backend_RESTFULL",
    img: backendREST.src,
    fork: false,
  },
  {
    id: "cerdyn-os",
    title: "CerdynOS",
    description:
      "Expense tracking system built with Tanstack Query, Zustand, React, Styled Components, as a daily expense tracker.",
    topics: [
      "@emotion/react",
      "@emotion/styled",
      "@mui/material",
      "@supabase/supabase-js",
      "@tanstack/react-query",
      "@tanstack/react-query-devtools",
      "chart.js",
      "dayjs",
      "emoji-picker-react",
      "firebase",
      "iso-country-currency",
      "react",
      "react-chartjs-2",
      "react-color",
      "react-content-loader",
      "react-dom",
      "react-hook-form",
      "react-icons",
      "react-lottie",
      "react-router-dom",
      "react-spinners",
      "styled-components",
      "sweetalert2",
      "swiper",
      "zustand",
    ],
    link: "https://control-gastos-b1017.web.app/login",
    img: "../../img/yop.webp",
    fork: false,
  },
  {
    id: "expense-tracker-cli",
    title: "expense-tracker-cli",
    description: "CLI application to track expenses.",
    topics: [
      "chalk-cli",
      "cli",
      "commanderjs",
      "csv-export",
      "inquirer",
      "inquirer-prompt",
      "node-fs",
      "tracker-expenses",
    ],
    link: "https://github.com/muke78/expense-tracker-cli",
    img: expenseTracker.src,
    fork: false,
  },
  {
    id: "hero-app",
    title: "HeroApp",
    description:
      "Frontend demo app showing how to create a functional page without a backend using React.",
    topics: [
      "chartjs",
      "framer-motion",
      "material-react-table",
      "motion-number",
      "query-string",
      "reac-icons",
      "reac-router-dom",
      "react",
      "vite",
    ],
    link: "https://heroappmkkh78.netlify.app/",
    img: heroApp.src,
    fork: false,
  },
  {
    id: "inventario-kinder",
    title: "Kindergarten-inventory",
    description:
      "Filter an inventory via CSV to get an accurate count of items that are no longer in use.",
    topics: [
      "inventory-management",
      "jupyter-notebook",
      "matplotlib",
      "pandas",
      "python",
    ],
    link: "https://github.com/muke78/Inventario-kinder",
    img: inventarioKinder.src,
    fork: false,
  },
  {
    id: "khelde-io",
    title: "khelde.io",
    description:
      "First development with weather API and first portfolio built with HTML, CSS, and JavaScript.",
    topics: ["css", "html", "javascript", "scrollreveal-js", "unicons"],
    link: "https://muke78.github.io/khelde.io/",
    img: kheldeIO.src,
    fork: false,
  },
  {
    id: "landing-page-cash-bank-con-astro",
    title: "Landing-Page-Cash-Bank-con-Astro",
    description: "Landing Page for Cash Bank created with Astro 4 and Tailwind.",
    topics: [
      "@astrojs/check",
      "@astrojs/tailwind",
      "astro",
      "tailwindcss",
      "typescript",
    ],
    link: "https://cash-bank.pages.dev/",
    img: cashBank.src,
    fork: true,
  },
  {
    id: "math-game",
    title: "Mathgame",
    description: "Math game with addition, subtraction, and multiplication.",
    topics: ["css", "html", "javascript", "javascript-game"],
    link: "https://mathgame-khelde.netlify.app/",
    img: mathGame.src,
    fork: false,
  },
  {
    id: "portafolio",
    title: "Portafolio",
    description:
      "Portfolio created with Astro 4 with React support for TypeScript, dynamic islands, and the @astrojs/tailwind library version 5.1.5.",
    topics: [
      "@astrojs/check",
      "@astrojs/node",
      "@astrojs/react",
      "@astrojs/tailwind",
      "@swup/astro",
      "@trivago/prettier-plugin-sort-imports",
      "@types/react",
      "animate.css",
      "astro",
      "daisyui",
      "flowbite",
      "react",
      "react-dom",
      "swup",
      "tailwindcss",
      "prettier",
    ],
    link: "",
    img: portafolio.src,
    fork: false,
  },
  {
    id: "sistema_numerico",
    title: "Number_System",
    description:
      "A small calculator to convert between different numerical bases in the computing system.",
    topics: [
      "binary",
      "calculator",
      "hexadecimal",
      "octal",
      "python",
      "tkinter-python",
    ],
    link: "https://github.com/muke78/Sistema_Numerico",
    img: calculadoraSistemaNumerico.src,
    fork: false,
  },
  {
    id: "task-tracker-cli",
    title: "task-tracker-cli",
    description: "CLI task tracker backend application.",
    topics: ["cli", "cli-app", "fs", "javascript", "path", "todolist"],
    link: "https://github.com/muke78/task-tracker-cli",
    img: taskTracker.src,
    fork: false,
  },
];
