export const experienceDataEN = [
  {
    id: "1",
    img: "/sleeplesscofi.webp",
    work: "Current",
    title: "Full Stack Developer",
    subtitle: "sleeplesscofi · Freelance",
    time: "Apr. 2024 · 8 months",
    location: "Lima, Peru · Remote",
    experience: [
      "Self-organization in GitHub to develop full web applications.",
      "Backend project to implement a clone of the social network Threads.",
      "Frontend project as the user interface for a Threads clone.",
      "Project for a complete kindergarten system with Backend and Frontend, including teacher login, management of parents and students, and evaluations.",
      "Backend task project to handle task states such as saving, updating, deleting, and retrieving tasks based on their status.",
      "Single-page application (SPA) for a bank to present company information.",
    ],
  },
  {
    id: "2",
    img: "/rimac.webp",
    work: "",
    title: "Database Developer",
    subtitle: "RIMAC (Risk Management) ICBA Mexico · Full-time",
    time: "Oct. 2023 - Apr. 2024 · 7 months",
    location: "Álvaro Obregón, Mexico City, Mexico · On-site",
    experience: [
      "Restructured the database to improve table management and enhance query performance by 30%.",
      "Managed RDS for Aurora MySQL database.",
      "Used Amplify as a container for the application's front-end.",
      "Used Lightsail as a back-end server container, including deploying changes via SSH.",
      "Programming in JavaScript and some TypeScript environments.",
      "Loaded data into MySQL from Python using the Conda package manager and Jupyter.",
      "Created modules with the React library, using Material UI as the design framework.",
    ],
  },
  {
    id: "3",
    img: "/piramide.webp",
    work: "",
    title: "Web Application Developer",
    subtitle: "Grupo Constructor Pirámide · Full-time",
    time: "Feb. 2023 - Sept. 2023 · 8 months",
    location: "Gustavo A. Madero, Mexico City, Mexico · On-site",
    experience: [
      "Database migration with relational databases.",
      "Performed SQL Server dumps for backup and mirroring between a test and a production database.",
      "Executed complex queries involving data partitions, daily aggregates, calculations, grouping, sorting, view creation, stored procedures, and triggers.",
      "Created complex reports in Power BI using SQL Server, including graphs, data tables, and DAX functions, improving the user interface by 60%.",
      "Implemented CRUD operations in PHP and routing.",
      "Implemented the Model-View-Controller (MVC) architecture, improving application speed by 70%.",
      "Created an interactive map with Leaflet in JavaScript, pulling data from SQL Server.",
      "Improved SEO by 50% for the application on both mobile and desktop devices.",
      "Created styles in CSS and SCSS for dark mode and light mode.",
      "Innovated logos and icons in the application, increasing visibility and accessibility by 20%.",
      "Used AWS to store information such as images and database backups.",
      "Maintained WordPress sites using plugins and creating backups.",
    ],
  },
  {
    id: "4",
    img: "/rutopia.webp",
    work: "",
    title: "Systems Assistant",
    subtitle: "Rutopía · Full-time",
    time: "Aug. 2022 - Oct. 2022 · 3 months",
    location: "Coyoacán, Mexico City, Mexico · On-site",
    experience: [
      "Created reports on the Tourplan platform.",
      "Managed activities on Monday.com.",
      "Developed dynamic reports.",
      "Basic use of GraphQL to compile information and consume APIs.",
    ],
  },
  {
    id: "5",
    img: "/hitech.webp",
    work: "",
    title: "Maintenance Specialist",
    subtitle: "SISTEMAS INTEGRALES HI-TECH · Full-time",
    time: "Jul. 2021 - Oct. 2021 · 4 months",
    location: "Tultitlán de Mariano Escobedo, Mexico · On-site",
    experience: [
      "Managed electronic components such as internal computer inventory, network inventory, computer equipment testing, cleaned computer equipment, configured printers, and maintained a server for Hyundai Trucks and Buses Perinorte.",
    ],
  },
];
