import backendERP from "@/img/BackeENDPir.webp";
import frontendERP from "@/img/FRntERP.webp";
import type { DataProjects } from "@/types/typesDataproyectos";

export const dataProyectosEmpresarialesFR: DataProjects[] = [
  {
    id: "erp-obra",
    title: "FrontEnd Obra",
    description:
      "Panneau d'administration pour le contrôle des travaux et des appels d'offres via un ERP",
    topics: [
      "php",
      "moment.js",
      "dropzone.js",
      "power BI",
      "chart.js",
      "datatables",
      "sweetalert2",
      "boostrap",
      "leaflet",
      "aws-sdk",
      "adminlte.js",
      "jwt-decode",
      "dotenv",
      "dotenv-webpack",
      "webpack",
      "webpack-cli",
      "webpack-dev-server",
    ],
    link: "Confidential",
    img: frontendERP.src,
    fork: false,
  },
  {
    id: "backend-obra",
    title: "BackEnd-ERP",
    description:
      "Partie logique du système pour la consommation depuis l'ERP via l'API RESTFULL",
    topics: [
      "async",
      "await",
      "axios",
      "bcrypt-nodejs",
      "bcryptjs",
      "body-parser",
      "dotenv",
      "express",
      "jsonwebtoken",
      "jwt-simple",
      "moment",
      "mongoose",
      "mssql",
      "nodemon",
      "socket.io",
      "swagger-jsdoc",
      "swagger-ui-express",
    ],
    link: "Confidential",
    img: backendERP.src,
    fork: false,
  },
  {
    id: "backEnd-aseguradora",
    title: "BackEnd Aseguradora",
    description:
      "Logique d'un comité administratif pour les risques d'assurance financière",
    topics: [
      "cors",
      "dotenv",
      "bcrypt-nodejs",
      "body-parser",
      "express",
      "jsonwebtoken",
      "mysql",
      "nodemon",
    ],
    link: "Confidential",
    img: backendERP.src,
    fork: false,
  },
];
