export const dataExperienceFR = [
  {
    id: "1",
    img: "/sleeplesscofi.webp",
    work: "Actuel",
    title: "Développeur Full Stack",
    subtitle: "sleeplesscofi · Freelance",
    time: "Avr. 2024 · 11 mois",
    location: "Lima, Pérou · À distance",
    experience: [
      "Organisation autonome sur GitHub pour développer des applications web complètes.",
      "Projet Backend pour implémenter un clone du réseau social Threads.",
      "Projet Frontend en tant qu'interface utilisateur pour un clone de Threads.",
      "Projet pour un système complet de jardin d'enfants avec Backend et Frontend, incluant la gestion des connexions des enseignants, des parents et des étudiants, et des évaluations.",
      "Projet Backend de gestion des états des tâches telles que l'enregistrement, la mise à jour, la suppression et la récupération des tâches en fonction de leur état.",
      "Application à page unique (SPA) pour une banque présentant les informations de l'entreprise.",
    ],
  },
  {
    id: "2",
    img: "/rimac.webp",
    work: "",
    title: "Développeur de bases de données",
    subtitle: "RIMAC (Risk Management) ICBA Mexique · Temps plein",
    time: "Nov. 2023 - Juil. 2024 · 7 mois",
    location: "Álvaro Obregón, Mexico, Mexique · Sur site",
    experience: [
      "Restructuration de la base de données pour améliorer la gestion des tables et optimiser les performances des requêtes de 30%.",
      "Gestion de RDS pour la base de données Aurora MySQL.",
      "Utilisation d'Amplify comme conteneur pour le front-end de l'application.",
      "Utilisation de Lightsail comme conteneur pour le back-end du serveur, y compris la mise en ligne des changements via SSH.",
      "Programmation en JavaScript et dans certains environnements TypeScript.",
      "Chargement des données dans MySQL depuis Python à l'aide du gestionnaire de packages Conda et de Jupyter.",
      "Création de modules avec la bibliothèque React en utilisant Material UI comme framework de conception.",
    ],
  },
  {
    id: "3",
    img: "/piramide.webp",
    work: "",
    title: "Développeur d'applications web",
    subtitle: "Grupo Constructor Pirámide · Temps plein",
    time: "Janv. 2023 - Nov. 2023 · 11 mois",
    location: "Gustavo A. Madero, Mexico, Mexique · Sur site",
    experience: [
      "Migration de bases de données avec des bases de données relationnelles.",
      "Dump SQL Server pour les sauvegardes et la mise en miroir entre une base de données de test et une base de données de production.",
      "Exécution de requêtes complexes incluant des partitions de données, des agrégats quotidiens, des calculs, des regroupements, des tris, la création de vues, des procédures stockées et des triggers.",
      "Création de rapports complexes dans Power BI avec SQL Server, incluant des graphiques, des tableaux de données et des fonctions DAX, améliorant l'interface utilisateur de 60%.",
      "Mise en œuvre des opérations CRUD en PHP et routage.",
      "Implémentation de l'architecture Modèle-Vue-Contrôleur (MVC), améliorant la vitesse de l'application de 70%.",
      "Création d'une carte interactive avec Leaflet en JavaScript, extrayant des données de SQL Server.",
      "Amélioration du SEO de 50% pour l'application sur les appareils mobiles et de bureau.",
      "Création de styles en CSS et SCSS pour les modes sombre et clair.",
      "Innovation dans les logos et les icônes de l'application, augmentant la visibilité et l'accessibilité de 20%.",
      "Utilisation d'AWS pour stocker des informations telles que des images et des sauvegardes de bases de données.",
      "Maintenance de sites WordPress en utilisant des plugins et en créant des sauvegardes.",
    ],
  },
  {
    id: "4",
    img: "/rutopia.webp",
    work: "",
    title: "Apprenti développeur",
    subtitle: "Rutopía · Temps plein",
    time: "Oct 2021 - Oct. 2022 · 1 an",
    location: "Coyoacán, Mexico, Mexique · Sur site",
    experience: [
      "Création de rapports sur la plateforme Tourplan.",
      "Gestion des activités sur Monday.com.",
      "Développement de rapports dynamiques.",
      "Utilisation de base de GraphQL pour compiler des informations et consommer des API.",
    ],
  },
];
