import backendTask from "@/img/BackendTask.webp";
import backendREST from "@/img/Backend_RESTFULL.webp";
import heroApp from "@/img/HeroApp.webp";
import calculadoraSistemaNumerico from "@/img/calculadoraSistemaNumerico.webp";
import cashBank from "@/img/cashBank.webp";
import cerdyn from "@/img/cerdyn.png";
import expenseTracker from "@/img/expense-tracker-cli.webp";
import inventarioKinder from "@/img/inventarioKinder.webp";
import kheldeIO from "@/img/kheldeio.webp";
import mathGame from "@/img/mathgame.webp";
import portafolio from "@/img/portafolio.webp";
import taskTracker from "@/img/taskTracker.webp";
import type { DataProjects } from "@/types/typesDataproyectos";

export const dataProyectosFR: DataProjects[] = [
  {
    id: "backend-task",
    title: "BackendTask",
    description:
      "Backend My Task Board devchallenges.io avec CRUD en mysql et postgresql complet pour les tâches et récupération des états selon la tâche",
    topics: [
      "backend-api",
      "crud-application",
      "expressjs",
      "mysql",
      "mysql2",
      "node",
      "nodejs",
      "postgres",
      "postgresql",
      "dotenv",
      "nodemon",
      "pg",
      "swagger-jsdoc",
      "swagger-ui-express",
    ],
    link: "https://github.com/muke78/BackendTask",
    img: backendTask.src,
    fork: false,
  },
  {
    id: "backend-rest-full",
    title: "Backend_RESTFULL",
    description:
      "Backend avec Express et Nodemon avec CRUD et JWT, Swagger avec téléchargement de fichiers, puis interface en React avec Zustand et Tanstack_query",
    topics: [
      "@formkit/tempo",
      "@trivago/prettier-plugin-sort-imports",
      "argon2",
      "backend",
      "backend-api",
      "crud-application",
      "express",
      "jwt-authentication",
      "jwt-token",
      "mysql2",
      "node",
      "nodemon",
      "rest-api",
      "swagger-jsdoc",
      "swagger-ui-express",
    ],
    link: "https://github.com/muke78/Backend_RESTFULL",
    img: backendREST.src,
    fork: false,
  },
  {
    id: "cerdyn-os",
    title: "CerdynOS",
    description:
      "Système de gestion des dépenses réalisé avec Tanstack Query, Zustand, React, Styled Components, comme portefeuille pour les dépenses quotidiennes",
    topics: [
      "@emotion/react",
      "@emotion/styled",
      "@mui/material",
      "@supabase/supabase-js",
      "@tanstack/react-query",
      "@tanstack/react-query-devtools",
      "chart.js",
      "dayjs",
      "emoji-picker-react",
      "firebase",
      "iso-country-currency",
      "react",
      "react-chartjs-2",
      "react-color",
      "react-content-loader",
      "react-dom",
      "react-hook-form",
      "react-icons",
      "react-lottie",
      "react-router-dom",
      "react-spinners",
      "styled-components",
      "sweetalert2",
      "swiper",
      "zustand",
    ],
    link: "https://control-gastos-b1017.web.app/login",
    img: cerdyn.src,
    fork: false,
  },
  {
    id: "expense-tracker-cli",
    title: "expense-tracker-cli",
    description: "Application CLI pour suivre les dépenses",
    topics: [
      "chalk-cli",
      "cli",
      "commanderjs",
      "csv-export",
      "inquirer",
      "inquirer-prompt",
      "node-fs",
      "tracker-expenses",
    ],
    link: "https://github.com/muke78/expense-tracker-cli",
    img: expenseTracker.src,
    fork: false,
  },
  {
    id: "hero-app",
    title: "HeroApp",
    description:
      "Application démonstration de création d'une page fonctionnelle frontend sans backend utilisant React",
    topics: [
      "chartjs",
      "framer-motion",
      "material-react-table",
      "motion-number",
      "query-string",
      "reac-icons",
      "reac-router-dom",
      "react",
      "vite",
    ],
    link: "https://heroappmkkh78.netlify.app/",
    img: heroApp.src,
    fork: false,
  },
  {
    id: "inventario-kinder",
    title: "Kindergarten-inventory",
    description:
      "Filtrage d'un inventaire à partir d'un fichier csv pour obtenir une estimation précise du nombre d'actifs obsolètes",
    topics: [
      "inventory-management",
      "jupyter-notebook",
      "matplotlib",
      "pandas",
      "python",
    ],
    link: "https://github.com/muke78/Inventario-kinder",
    img: inventarioKinder.src,
    fork: false,
  },
  {
    id: "khelde-io",
    title: "khelde.io",
    description:
      "Premier développement avec une API météo et premier portfolio créé avec HTML, CSS et JavaScript",
    topics: ["css", "html", "javascript", "scrollreveal-js", "unicons"],
    link: "https://muke78.github.io/khelde.io/",
    img: kheldeIO.src,
    fork: false,
  },
  {
    id: "landing-page-cash-bank-con-astro",
    title: "Landing-Page-Cash-Bank-con-Astro",
    description:
      "Page de destination de Cash Bank créée avec Astro 4 et Tailwind",
    topics: [
      "@astrojs/check",
      "@astrojs/tailwind",
      "astro",
      "tailwindcss",
      "typescript",
    ],
    link: "https://cash-bank.pages.dev/",
    img: cashBank.src,
    fork: true,
  },
  {
    id: "math-game",
    title: "Mathgame",
    description:
      "Jeu de mathématiques avec des additions, soustractions et multiplications",
    topics: ["css", "html", "javascript", "javascript-game"],
    link: "https://mathgame-khelde.netlify.app/",
    img: mathGame.src,
    fork: false,
  },
  {
    id: "portafolio",
    title: "Portafolio",
    description:
      "Portfolio créé avec Astro 4 avec support React pour TypeScript, Dynamic Islands et la bibliothèque @astrojs/tailwind en version 5.1.5",
    topics: [
      "@astrojs/check",
      "@astrojs/node",
      "@astrojs/react",
      "@astrojs/tailwind",
      "@swup/astro",
      "@trivago/prettier-plugin-sort-imports",
      "@types/react",
      "animate.css",
      "astro",
      "daisyui",
      "flowbite",
      "react",
      "react-dom",
      "swup",
      "tailwindcss",
      "prettier",
    ],
    link: "",
    img: portafolio.src,
    fork: false,
  },
  {
    id: "sistema_numerico",
    title: "Number_System",
    description:
      "Petit calculateur pour convertir d'un système numérique à un autre, du système numérique informatique",
    topics: [
      "binary",
      "calculator",
      "hexadecimal",
      "octal",
      "python",
      "tkinter-python",
    ],
    link: "https://github.com/muke78/Sistema_Numerico",
    img: calculadoraSistemaNumerico.src,
    fork: false,
  },
  {
    id: "task-tracker-cli",
    title: "task-tracker-cli",
    description: "Backend depuis la CLI d'un suivi de tâches",
    topics: ["cli", "cli-app", "fs", "javascript", "path", "todolist"],
    link: "https://github.com/muke78/task-tracker-cli",
    img: taskTracker.src,
    fork: false,
  },
];
