#!/bin/sh

echo "🔍 Verificando archivos antes del commit..."

# # Bloquear commits de archivos .env
# if git diff --cached --name-only | grep -q ".env"; then
#   echo "❌ No puedes hacer commit de archivos .env"
#   exit 1
# fi

# Formatear código antes del commit
echo "🚀 Ejecutando Prettier..."
pnpm run prettier --write .


# Verificar que el código esté actualizado antes del push
echo "🔄 Verificando que tu código esté actualizado..."
if ! git pull; then
  echo "❌ Error al actualizar el código. Revisa los conflictos."
  exit 1
fi

echo "✅ Código actualizado. Todo listo para el commit."
