export const dataProyectos = [
  {
    id: "erp-obra",
    title: "FrontEnd Obra",
    description:
      "Panel de administracion para un control de obras y de licitaciones por medio de un ERP",
    topics: [
      "aws-sdk",
      "jwt-decode",
      "dotenv",
      "dotenv-webpack",
      "webpack",
      "webpack-cli",
      "webpack-dev-server",
    ],
    link: "Confidential",
    img: "../../img/yop.webp",
    fork: false,
  },
  {
    id: "backend-obra",
    title: "BackEnd-ERP",
    description:
      "Parte logica del sistema para consumo desde el ERP por medio de API RESTFULL",
    topics: [
      "async",
      "await",
      "axios",
      "bcrypt-nodejs",
      "bcryptjs",
      "body-parser",
      "dotenv",
      "express",
      "jsonwebtoken",
      "jwt-simple",
      "moment",
      "mongoose",
      "mssql",
      "nodemon",
      "socket.io",
      "swagger-jsdoc",
      "swagger-ui-express",
    ],
    link: "Confidential",
    img: "../../img/yop.webp",
    fork: false,
  },
  {
    id: "backEnd-aseguradora",
    title: "BackEnd Aseguradora",
    description:
      "Logica de un panel administrativo para riesgos de seguros financieros",
    topics: [
      "cors",
      "dotenv",
      "bcrypt-nodejs",
      "body-parser",
      "express",
      "jsonwebtoken",
      "mysql",
      "nodemon",
    ],
    link: "Confidential",
    img: "../../img/yop.webp",
    fork: false,
  },
];
