export const dataExperiencia = [
  {
    id: "1",
    img: "/sleeplesscofi.webp",
    work: "Actual",
    title: "Desarrollador full stack",
    subtitle: "sleeplesscofi · Autónomo",
    time: "abr. 2024 · 8 meses",
    location: "Lima, Perú · En remoto",
    experience: [
      "Organización autónoma en GitHub para desarrollar aplicaciones completas web",
      "Proyecto de Backend para hacer funcionar un clon de la red social de Threads",
      "Proyecto frontend como vista para el usuario de un clon de Threads",
      "Proyecto de un jardín de niños completo con Backend y Frontend para funciones de guardar maestros login, llevar un control de papás y estudiantes y evaluaciones",
      "Proyecto de un backend task para manejar los estados de las tareas como guardar, actualizar y eliminar y traer tareas por estados según la tarea",
      "Single page aplication(SPA) de un banco para presentación de compañía",
    ],
  },
  {
    id: "2",
    img: "/rimac.webp",
    work: "",
    title: "Desarrollador bases de datos",
    subtitle: "RIMAC (Risk Management) ICBA México · Jornada completa",
    time: "oct. 2023 - abr. 2024 · 7 meses",
    location: "Álvaro Obregón , Cuidad de México, México, Prsencial",
    experience: [
      "Re estructuración de la base de datos, para poder llevar un mejor control de las tablas, mejorando un rendimiento en las consultas de 30%",
      "Administración de RDS para la base de datos en Aurora MySQL.",
      "Amplify como contenedor del front-end de la aplicación.",
      "Lightsail como contenedor de back-end del servidor, así como subir cambios desde SSH.",
      "Programación en lenguaje de JavaScript y pequeños entornos de TypeScript.",
      "Carga de datos a MySQL desde python desde su sistema de gestor de paquetes conda ocupando Jupyter",
      "Creación de módulos con la librería react ocupando Material UI como framework de diseño.",
    ],
  },
  {
    id: "3",
    img: "/piramide.webp",
    work: "",
    title: "Desarrollador de aplicaciones web",
    subtitle: "Grupo Constructor Pirámide · Jornada completa",
    time: "feb. 2023 - sept. 2023 · 8 meses",
    location: "Gustavo A. Madero, Ciudad de México, México · Presencial",
    experience: [
      "Migración de base de datos con base de datos relacional",
      "Dump SQL Server para respaldo y espejo de una base de pruebas y una de producción",
      "Consultas a un nivel complejo trayendo particiones de datos, acumulados por día, cálculos incluidos dentro de las consultas, agrupaciones, ordenamiento de datos, creación de vistas, de store procedure y triggers.",
      "Creación de reportes en Power BI con SQL Server, reportes complejos de gráficos como curvas, tablas de información y consumo de algunas funciones en DAX logrando mejorar la interfaz en un 60%",
      "Inserción de registros (CRUD) en PHP y enrutamiento",
      "Implementación de Modelo, Vista, Controlador (MVC) mejorando un 70% la rapidez de la aplicación",
      "Mapa interactivo con Leaflet en JavaScript con datos desde SQL Server",
      "Mejorando el SEO en un 50% en la aplicación para los dispositivos móviles y de escritorio",
      "Generación de estilos en CSS y SCSS con estilos para dark mode y light mode",
      "Innovación de logotipos y iconos en la aplicación con un aumento del 20% en la visibilidad y accesibilidad del usuario",
      "Utilización de AWS para guardar información como imágenes, espejos de la base de datos",
      "Mantenimiento a páginas de WordPress utilizando plugins y creación de respaldos",
    ],
  },
  {
    id: "4",
    img: "/rutopia.webp",
    work: "",
    title: "Auxiliar de sistemas",
    subtitle: "Rutopía · Jornada completa",
    time: "ago. 2022 - oct. 2022 · 3 meses",
    location: "Coyoacán, Ciudad de México, México · Presencial",
    experience: [
      "Creación de reportes en la plataforma Tourplan.",
      "Control de actividades en Monday.",
      "Desarrollo de reportes dinámicos.",
      "Uso básico de GraphQL para compilar información y consumir API.",
    ],
  },
  {
    id: "5",
    img: "/hitech.webp",
    work: "",
    title: "Especialista en mantenimiento",
    subtitle: "SISTEMAS INTEGRALES HI-TECH · Jornada completa",
    time: "jul. 2021 - oct. 2021 · 4 meses",
    location: "Tultitlan de Mariano Escobedo, México, México · Presencial",
    experience: [
      "Administración de componentes electrónicos como inventario interno de las computadoras, inventario de redes y prueba de equipos de cómputo, limpieza a equipos de cómputo configuración de impresoras y de un servidor en la empresa Hyundai Camiones Y Buses Perinorte.",
    ],
  },
];
